### ISSUE TITLE
Rain particles fall too slow

### ISSUE THREAD

**Issue by Fixer-007** [paramat/snowdrift#8]
Fall speed boost is needed, maybe up to 1.5-2x times of current value.

**Comment by paramat** [comment]
They look slow, but actually the fall speed is 10n/s and 10m/s is a typical terminal velocity for a large raindrop, see https://hypertextbook.com/facts/2007/EvanKaplan.shtml. I think it's a kind of illusion caused by the big textures being visible further away.

**Comment by paramat** [comment]
Another interesting fact:
"A common misconception is the shape of the raindrop. It is often depicted as pointy and lopsided. However, research has found the shape of a raindrop to be rather spherical or slightly flattened on the bottom by airflow like a hamburger bun."

**Comment by Fixer-007** [comment]
Possibly, still felt weird.

**Comment by paramat** [comment]
Looking at that link 12 would be ok and a higher speed would help in other ways too, so i'll increase it a little to 12. They are after all huge drops :)
