### ISSUE TITLE
altitude compatability

### ISSUE THREAD

**Issue by morlanius** [paramat/snowdrift#9]
https://github.com/paramat/snowdrift/blob/568964eabf72d169bb3d7d8a2eb4beba863c5504/init.lua#L122

I have other sky boxes at altitude so i have this 
if math.random() < 0.1 and ppos.y < 3000 then

here, and further down so that its not changing the sky constantly and the two mods conflicting. could add an variable in here that someone could config as a cut-off height for weather and skybox changes. default it to -1 and have no height limit.

**Comment by paramat** [comment]
Yes valid issue, but i no longer maintain this mod. I suggest forking and improving this mod yourself.
